server:
  port: 9000
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
        routes:
        - id: clientservice1
          uri: lb://clientservice1
          predicates:
            - Path=/service1/**
        - id: config-server
          uri: lb://CONFIG-SERVER
          predicates:
            - Path=/config/**
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/